services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=asdd
    ports:
      - 5432:5432
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=asdd
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  auction-svc:
    image: services/auction-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 7001:7001
      - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: services/search-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 7002:7002
    depends_on:
      - mongodb
      - rabbitmq
  identity-svc:
    image: services/identity-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5000:5000
    depends_on:
      - postgres
  gateway-svc:
    image: services/gateway-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/GatewayServices/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 6001:6001
  bid-svc:
    image: services/bid-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 7003:7003
    depends_on:
      - mongodb
      - rabbitmq
  notify-svc:
    image: services/notify-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 7004:7004
    depends_on:
      - rabbitmq
