services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=asdd
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=asdd
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    # restart: always
    restart: always
  auction-svc:
    image: services/auction-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - RabbitMq__VirtualHost=/
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - ConnectionStrings__default=Server=postgres:5432;User Id=postgres;Password=asdd;Database=auctions
      - IdentityServer__Authority=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: services/search-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - RabbitMq__VirtualHost=/
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - ConnectionStrings__default=mongodb://root:asdd@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
  identity-svc:
    image: services/identity-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=asdd;Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway-svc:
    image: services/gateway-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/GatewayServices/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
  bid-svc:
    image: services/bid-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - RabbitMq__VirtualHost=/
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - ConnectionStrings__default=mongodb://root:asdd@mongodb
      - IdentityServer__Authority=http://identity-svc
      - GrpcServer__Auction=http://auction-svc:7777
    ports:
      - 7003:80
    depends_on:
      - mongodb
      - rabbitmq
  notify-svc:
    image: services/notify-svc:latest
    restart: always
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - RabbitMq__VirtualHost=/
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    ports:
      - 7004:80
    depends_on:
      - rabbitmq

volumes:
  pgdata:
  mongodata:
